# Generated by Django 3.2.7 on 2021-09-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='empresa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
