# Generated by Django 3.2.7 on 2021-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210929_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
